// Synthetic sessions used to build the demo fixture home.
//
// Nothing here is real. The projects, prompts and replies are invented so the
// demo recording can be regenerated by anyone without exposing a real machine's
// session history. `ago` is minutes before "now" at build time, which drives
// both the ordering in the picker and the timestamp label.
//
// `tool` is either "opencode" or the name of a Claude account ("cc1" / "cc2")
// or a Codex account ("cx1" / "cx2").
//
// `title` is what OpenCode and Claude store alongside the session. Codex stores
// no title, so a Codex row is titled by its opening prompt and the title here
// is only a label for whoever is editing this file.

const NEBULA = "~/code/nebula-api"
const AURORA = "~/code/aurora-web"
const FORGE = "~/code/pixel-forge"
const DOTS = "~/dotfiles"

export const sessions = [
  {
    tool: "cc1",
    ago: 12,
    dir: NEBULA,
    title: "Rotate refresh tokens on reuse",
    turns: [
      ["user", "Our refresh tokens never rotate. If one leaks it is valid until it expires. Add reuse detection."],
      ["assistant", "Reading internal/auth/token.go. The refresh handler validates the JWT and mints a new access token, but hands the same refresh token back, so there is nothing to detect reuse against."],
      ["user", "Right. Rotate on every use and revoke the whole family if an old one comes back."],
      ["assistant", "Added a token_family table keyed by family_id, with each rotation storing the superseded jti. RefreshHandler now issues a new refresh token and marks the old jti consumed; presenting a consumed jti revokes every token in that family and returns 401."],
      ["user", "What happens when the client retries after a dropped response?"],
      ["assistant", "That is the sharp edge: a lost response looks identical to theft. Added a 10 second grace window where replaying the immediately-previous jti returns the same rotated pair instead of nuking the family. Beyond the window it is treated as reuse."],
    ],
  },
  {
    tool: "opencode",
    ago: 41,
    dir: AURORA,
    title: "Auth redirect loops on expired session",
    turns: [
      ["user", "Users with an expired session bounce between /login and /dashboard forever. Chrome eventually gives up with ERR_TOO_MANY_REDIRECTS."],
      ["assistant", "The loop is in useRequireAuth. It redirects to /login whenever `user` is null, but `user` is also null while the session query is still loading, so the login page immediately redirects back on its own auth check."],
      ["user", "So we need a third state, not just null vs user."],
      ["assistant", "Yes. Changed the hook to return status: 'loading' | 'authed' | 'anon' and only redirect on 'anon'. The route guard renders a skeleton while loading. Loop is gone in the repro."],
      ["user", "Add a test that fails on the old code."],
      ["assistant", "Added guard.test.tsx: mounts the guard with a query stuck in loading and asserts navigate was never called. It fails against the previous implementation and passes now."],
    ],
  },
  {
    tool: "cx1",
    ago: 63,
    dir: NEBULA,
    title: "Rate limiter counts retries as new requests",
    turns: [
      ["user", "The rate limiter rejects clients well under their quota."],
      ["assistant", "It counts SDK retries as fresh requests. The limiter increments in the middleware before the handler runs, and the SDK retries a 503 three times, so one logical call burns four tokens from the bucket."],
      ["user", "Can we make the retries idempotent against the bucket?"],
      ["assistant", "Added an Idempotency-Key header the SDK reuses across retries of the same call. The limiter now increments once per key and stores the outcome for 60s, so retries read the cached decision instead of paying again."],
      ["user", "What if a client never sends the header?"],
      ["assistant", "Falls back to the old per-request counting, so nothing gets more permissive by omitting it. Logged a metric for keyless traffic so we can see who to nudge."],
    ],
  },
  {
    tool: "cc2",
    ago: 95,
    dir: FORGE,
    title: "Parallel PNG encoding with rayon",
    turns: [
      ["user", "pixel-forge takes 40s to process a 500 image batch. It is single threaded. Can we use rayon?"],
      ["assistant", "The pipeline is decode, resize, encode per file with no shared state between files, so it is embarrassingly parallel. Swapped the outer `for` in batch.rs for `par_iter` and collected results into a Vec<Result<_>>."],
      ["user", "How much did that buy us?"],
      ["assistant", "12.3s on 8 cores, down from 41.7s. Not the 8x you might hope for because the encoder allocates a fresh buffer per image and the allocator becomes the contention point."],
      ["user", "Can we reuse the buffers?"],
      ["assistant", "Added a thread_local scratch buffer reused across images in the same worker. 9.1s now. The remaining gap is real decode work, so this is close to the floor without changing codecs."],
    ],
  },
  {
    tool: "cc1",
    ago: 180,
    dir: NEBULA,
    title: "Postgres connection pool exhaustion under load",
    turns: [
      ["user", "Under load tests we hit 'sorry, too many clients already' after about 90 seconds. Pool size is 25, Postgres max_connections is 100."],
      ["assistant", "Found it in metrics.go: the background metrics collector opens its own sql.DB every tick instead of reusing the shared pool, and never closes it. Every 5 seconds that leaks up to 25 more connections."],
      ["user", "That would do it. Was it always like that?"],
      ["assistant", "It came in with the metrics work three weeks ago. The leak needs sustained load to show up, which is why it survived CI."],
      ["user", "Fix it and add something that would have caught it."],
      ["assistant", "Collector now takes the shared *sql.DB. Added a test that asserts db.Stats().OpenConnections stays flat across 20 collector ticks; it climbs to 40+ on the old code."],
    ],
  },
  {
    tool: "opencode",
    ago: 300,
    dir: AURORA,
    title: "Virtualize the results table",
    turns: [
      ["user", "The results table renders 4000 rows at once and typing in the filter box is unusable. Every keystroke drops frames."],
      ["assistant", "Two separate problems. The DOM has 4000 rows so every re-render is expensive, and the filter runs on the unmemoized full array on each keystroke."],
      ["user", "Do the windowing first, that is the big one."],
      ["assistant", "Swapped the tbody for react-window's FixedSizeList at 36px rows. DOM node count drops from ~4000 to ~30. Sticky header needed to move out of the scroll container to survive the change."],
      ["user", "Typing still stutters a bit."],
      ["assistant", "That is the second problem. Memoized the filtered array on [rows, query] and moved the query into a deferred value so typing stays responsive while the list catches up. Smooth now."],
    ],
  },
  {
    tool: "cc1",
    ago: 460,
    dir: NEBULA,
    title: "Structured logging with request correlation",
    turns: [
      ["user", "Our logs are fmt.Printf soup. I cannot trace one request across handlers. Move to slog with a request id."],
      ["assistant", "Added a middleware that pulls X-Request-Id or generates a UUIDv7, stores a slog.Logger with that id in the request context, and sets the header on the response."],
      ["user", "Do I have to thread the logger through every function now?"],
      ["assistant", "Only through ctx, which you are already passing. Added log.From(ctx) that falls back to the default logger when nothing is in context, so a missed wiring degrades instead of panicking."],
      ["user", "Replace the existing Printf calls too."],
      ["assistant", "Converted 63 call sites across 14 files. Levels assigned by content: request lifecycle at Info, retries and degraded paths at Warn, anything returning 5xx at Error. Health check logging dropped to Debug because it was 80% of the volume."],
    ],
  },
  {
    tool: "cc2",
    ago: 720,
    dir: DOTS,
    title: "Neovim LSP config is loading twice",
    turns: [
      ["user", "gopls starts two instances on every Go file. Nothing obvious in my config does setup twice."],
      ["assistant", "It is loading twice through different paths. lsp.lua calls lspconfig.gopls.setup and the ftplugin/go.lua added last month also calls it. The ftplugin runs per buffer so you get a second client attached."],
      ["user", "Which one should win?"],
      ["assistant", "Keep the central lsp.lua. The ftplugin only existed to set gofumpt, which belongs in the gopls settings table anyway. Moved the setting and deleted the ftplugin."],
      ["user", "Confirmed, one client now. Thanks."],
    ],
  },
  {
    tool: "opencode",
    ago: 1100,
    dir: FORGE,
    title: "Deterministic output for the same input",
    turns: [
      ["user", "Running pixel-forge twice on the same directory produces different output hashes. That breaks our build cache."],
      ["assistant", "Two sources of nondeterminism. read_dir returns entries in filesystem order, and the PNG encoder writes a tIME chunk with the current timestamp."],
      ["user", "Both need to go."],
      ["assistant", "Sorting entries by path after read_dir, and disabled the tIME chunk. Ten consecutive runs now produce identical sha256 for the whole output tree."],
      ["user", "Is there a way to catch a regression here?"],
      ["assistant", "Added an integration test that runs the pipeline twice into separate temp dirs and asserts the hash trees match. It is quick because the fixture set is small."],
    ],
  },
  {
    tool: "cc1",
    ago: 1600,
    dir: AURORA,
    title: "CSP blocks the analytics bundle",
    turns: [
      ["user", "After enabling CSP the analytics script is blocked. I do not want to add unsafe-inline just to make it go away."],
      ["assistant", "The bundle itself loads fine; what is blocked is the inline bootstrap snippet in index.html. That is why unsafe-inline looks like the fix."],
      ["user", "What is the alternative?"],
      ["assistant", "Per-response nonce. The server generates one, puts it in the CSP header and on the script tag. Kept a hash-based fallback for the static prerendered pages where there is no server to generate a nonce."],
      ["user", "Does that work with the dev server?"],
      ["assistant", "Added the same nonce logic to the dev middleware so dev and prod fail the same way. Previously CSP was off in dev, which is how this reached staging unnoticed."],
    ],
  },
  {
    tool: "cc2",
    ago: 2300,
    dir: DOTS,
    title: "zsh startup takes 900ms",
    turns: [
      ["user", "New shells take almost a second to appear. Where is the time going?"],
      ["assistant", "zprof says nvm.sh is 610ms of it, all in sourcing the script itself, not in any command you run."],
      ["user", "I use node constantly though."],
      ["assistant", "Replaced eager sourcing with a lazy shim: node, npm, npx and yarn are stubs that source nvm on first call and then re-exec. First node command costs the 610ms once, every shell after that starts in 190ms."],
      ["user", "Anything else worth trimming?"],
      ["assistant", "compinit rebuilds the completion dump on every start. Guarding it to rebuild once a day takes another 40ms off, so about 150ms total."],
    ],
  },
  {
    tool: "opencode",
    ago: 3000,
    dir: NEBULA,
    title: "Idempotency keys for the payments endpoint",
    turns: [
      ["user", "A client retried a timed-out payment request and got charged twice. We need idempotency keys."],
      ["assistant", "Handler currently treats each POST as new work. Added an Idempotency-Key header stored with the request fingerprint and the serialized response."],
      ["user", "What about two identical requests arriving at the same time?"],
      ["assistant", "The interesting case. A unique index on the key means the second insert loses; that request waits on the first via advisory lock and returns the stored response rather than doing the work again."],
      ["user", "And if the key is reused with a different body?"],
      ["assistant", "422 with a clear message. Reusing a key for different work is a client bug and silently returning the old response would hide it."],
    ],
  },
  {
    tool: "cc1",
    ago: 4200,
    dir: FORGE,
    title: "Ship static musl binaries from CI",
    turns: [
      ["user", "Our release binaries fail on Alpine with 'not found' even though the file exists. glibc thing?"],
      ["assistant", "Yes. The binary is dynamically linked against glibc and Alpine ships musl, so the loader is missing. The confusing error is the loader, not your binary."],
      ["user", "Build static then."],
      ["assistant", "Added x86_64-unknown-linux-musl to the release workflow via cross. Binary is 4.1MB static and runs on Alpine, Debian and a scratch container."],
      ["user", "Keep the glibc build too?"],
      ["assistant", "Kept both. musl's allocator is measurably slower under the parallel workload, so the glibc build stays the default download and musl is the portable fallback."],
    ],
  },
  {
    tool: "cx2",
    ago: 4200,
    dir: FORGE,
    title: "Colour profiles dropped on resize",
    turns: [
      ["user", "Resized JPEGs come out washed out."],
      ["assistant", "The originals carry an Adobe RGB profile and the outputs are tagged as nothing, so viewers assume sRGB. The resize path decodes to a raw buffer and re-encodes without copying the ICC chunk."],
      ["user", "Carry the profile through, or convert to sRGB?"],
      ["assistant", "Convert. Carrying Adobe RGB through means every downstream consumer has to be colour-managed. Added an lcms2 transform to sRGB during resize and tag the output explicitly."],
      ["user", "Does that slow the batch down much?"],
      ["assistant", "About 4% on the 500 image batch. The transform is cached per source profile, so it only builds once per distinct input profile rather than per image."],
    ],
  },
  {
    tool: "opencode",
    ago: 5800,
    dir: AURORA,
    title: "Flaky date test fails only in CI",
    turns: [
      ["user", "formatRelative test passes locally and fails in CI about one run in three."],
      ["assistant", "The test builds a date with new Date('2026-03-14') and asserts '3 months ago'. CI runs UTC, your machine is UTC+2, so the local date lands on a different day and the boundary flips."],
      ["user", "So it is timezone, not timing."],
      ["assistant", "Both, slightly. The timezone makes it wrong and the month boundary makes it intermittent. Pinned TZ=UTC in the test setup and used explicit UTC constructors in the fixtures."],
      ["user", "Any others like it?"],
      ["assistant", "Grepped for bare date literals in tests and found four more in the reporting suite. Converted them the same way."],
    ],
  },
  {
    tool: "cc2",
    ago: 8600,
    dir: DOTS,
    title: "Split the git config per-directory",
    turns: [
      ["user", "I keep committing to work repos with my personal email. Can git pick the identity from the path?"],
      ["assistant", "Yes, conditional includes. Added includeIf gitdir:~/work/ and includeIf gitdir:~/personal/ pointing at separate identity files, and removed the global user.email so a missed path fails loudly instead of using the wrong one."],
      ["user", "Does that cover signing keys too?"],
      ["assistant", "Included them in the same files, so work commits sign with the work key automatically. Verified by committing in both trees and checking git log --show-signature."],
    ],
  },
]
